steps:
  # Build Docker image with secret mount (Flutter build needs secret access)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'API_KEY=$$API_KEY',
      '-t', 'gcr.io/$PROJECT_ID/apb-ta-new:$COMMIT_SHA',
      '.'
    ]
    secretEnv: ['API_KEY']

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/apb-ta-new:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'apb-ta-new'
      - '--image'
      - 'gcr.io/$PROJECT_ID/apb-ta-new:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/apb-ta-new:$COMMIT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

timeout: '1200s'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/api-key/versions/latest
      env: 'API_KEY'
