steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'API_KEY=$$API_KEY',
      '-t', 'gcr.io/$PROJECT_ID/apb_ta_new',
      '.'
    ]
    secretEnv: ['API_KEY']
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/apb-ta-new:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'apb-ta-new'
      - '--image'
      - 'gcr.io/$PROJECT_ID/apb-ta-new:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/apb-ta-new:$COMMIT_SHA'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

# Timeout for the entire build
timeout: '1200s'
substitutions:
  _API_KEY: 'your-api-key-here'
  _FIREBASE_KEY: 'your-firebase-key-here'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/api-key/versions/latest
    env: 'API_KEY'