steps:
  # Test basic docker functionality
  - name: 'gcr.io/cloud-builders/docker'
    args: ['--version']
  
  # List files in current directory
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'ls -la']
  
  # Test simple build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'test-image', '.']
    timeout: '600s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'